# Generated by Django 5.2.2 on 2025-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amnt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("term", models.CharField(max_length=20)),
                ("grade", models.CharField(max_length=2)),
                ("funded_amnt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("default_flag", models.BooleanField()),
            ],
        ),
    ]
